In [1]:
import pandas as pd

df = pd.read_csv('../data/processed/heart_disease_cleaned.csv')
df.head()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [ ]:
# Composite Lifestyle Risk Score
df['lifestyle_risk_score'] = (
    df['Smoker'] +
    (1 - df['PhysActivity']) +
    (1 - df['Fruits']) +
    (1 - df['Veggies']) +
    (df['HvyAlcoholConsump']) 

)

df['lifestyle_risk_score'].value_counts()

lifestyle_risk_score
1.0    80532
2.0    58842
0.0    53363
3.0    28579
4.0     7977
5.0      488
Name: count, dtype: int64

In [3]:
# Comorbidity Count

df['has_diabetes'] = (df['Diabetes'] > 0).astype(int)
df['comorbidity_count'] = df['HighChol'] + df['has_diabetes']

df['comorbidity_count'].value_counts()

comorbidity_count
0.0    114917
1.0     88494
2.0     26370
Name: count, dtype: int64

In [4]:
# PH-Aligned BMI Category

def bmi_category_ph(bmi):
    if bmi < 18.5:
        return 0
    elif bmi < 23:
        return 1
    elif bmi < 27:
        return 2
    else:
        return 3

df['bmi_cat_ph'] = df['BMI'].apply(bmi_category_ph)

In [5]:
# Confirm Ordinal Columns 

df[['GenHlth', 'MentHlth', 'PhysHlth', 'Age', 'Education', 'Income']].describe()

,GenHlth,MentHlth,PhysHlth,Age,Education,Income
count,229781.000000,229781.000000,229781.000000,229781.000000,229781.000000,229781.000000
mean,2.601151,3.505373,4.675178,8.086582,4.980568,5.890383
std,1.064685,7.713725,9.046568,3.093809,0.992895,2.092477
min,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,2.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,3.000000,0.000000,0.000000,8.000000,5.000000,6.000000
75%,3.000000,2.000000,4.000000,10.000000,6.000000,8.000000
max,5.000000,30.000000,30.000000,13.000000,6.000000,8.000000

In [6]:
# Save Feature-Engineered Data

df.to_csv('../data/processed/heart_disease_features.csv', index=False)